### ISSUE TITLE
some questions 

### ISSUE THREAD

**Issue by dananothername** [TASVideos/pcem#9]
i need some tips to make pcem work in libTAS
what i reached now is
![Screenshot_2022-07-09-10-32-14-645_com android chrome](https://user-images.githubusercontent.com/101902085/178100180-a7841c06-9c40-46b5-8f7e-d15ef72d634b.png)
where to put those roms 
what the directory `./pcem/folder` is

**Comment by vadosnaprimer** [comment]
https://tasvideos.org/EmulatorResources/PCem
